### ISSUE TITLE
Table limit 40 in a ledger; Both ACTIVE & INACTIVE

### ISSUE THREAD

**Issue by KotoJallow** [awslabs/amazon-qldb-driver-nodejs#14]
**_### Error via nodejs driver_**
BadRequestException: Exceeded tables limit: Ledger has 40 total tables, and cannot create another.
### **_Error via console_**
Start query error
Exceeded tables limit: Ledger has 40 total tables, and cannot create another (Service: AmazonQLDBSession; Status Code: 400; Error Code: BadRequestException; Request ID: ...)

It seems there is a limit of 40 tables in a ledger. Even though
` select  * from information_schema.user_tables = 40.
`
However, I have 9 ACTIVE tables.
`select  * from information_schema.user_tables where status='ACTIVE' = 9 results
`
This is a QLDB general issue as dropped tables are stored in _### ###information_schema.user_tables_ as INACTIVE and affects the limit.

How do you plan to solve this?
Is there a way of completely deleting a table or if not so, then let only the ACTIVE tables affect the table limit of 40 or what is the wisdom behind the limit?

@saumehta9 @othonrsanchez @jpeddicord @ovalba @jamesiri @ajorg-aws @osa-3p-prod

**Comment by yohanmartin** [comment]
Thanks for raising this issue. We will certainly look into options for increasing this limit based on our understanding of your use case(s). Please open a support case with AWS Support to share any use case details that are deemed confidential. Otherwise, please feel free to share details that we can review. A ledger is an immutable store and can be expected to store data associated with a specific business domain or operational domain (for example: a ledger named “Cross-border Payments” would have tables storing data entirely separate from the ledger for “Employee Payroll Audit”, and similar). We would be keen to understand how you are approaching the ledger and table design aspects that are specific to your use case(s).

**Comment by KotoJallow** [comment]
Thank you. 
> We will certainly look into options for increasing this limit based on our understanding of your use case(s)> is that going to be an increased per user requirement?

> (for example: a ledger named “Cross-border Payments” would) >

That's a good example but given a maximum of 5 ledgers, 40 tables per each. It means at most 5 projects, given a ledger per project. Right now, I have all the tables for a certain project in one ledger being in dev stage often tables are deleted and the summation of deleted ledgers + actives ones cannot exceed 40, which totally makes that ledger unusable consequently having it deleted which leads to a loss of data. Exported the journal does it include inactive tables too? If so, then I guess you should help us with another solution.  What is the motivation behind the limit 40 counting both active and inactive(deleted) tables?
For the ledgers too, initially, it had a limit of 10 now it's 5.

**Comment by aurghob33** [comment]
Hi @KotoJallow, 
Apologies for the delayed reply. 
We generally recommend having a separate dev account for non-prod work. 

>Exported the journal does it include inactive tables too?

The journal keeps track of all the updates to the ledger so theoretically, if the exported journal is imported back into QLDB, it would still include the inactive tables.
Out of curiosity, how would you use the export journal feature? What would you do after you have exported it ?

>What is the motivation behind the limit 40 counting both active and inactive(deleted) tables?

We count inactive tables as part of 40 tables limit since we also allow our customers to [undrop a table](https://docs.aws.amazon.com/qldb/latest/developerguide/ql-reference.undrop-table.html).

>For the ledgers too, initially, it had a limit of 10 now it's 5.

QLDB had a 10 ledger limit during preview but a 5 ledger limit after General Availability. 
As discussed [here](https://docs.aws.amazon.com/qldb/latest/developerguide/limits.html), the 5 ledger limit is a soft limit per region per account. To request a quota increase for your account in a Region, please do so through the Service Quotas console at https://console.aws.amazon.com/servicequotas/.

Do let me know if you have other questions related to this issue that you would like to have answered.

**Comment by KotoJallow** [comment]
@aurghob33 Thank you. 
`What would you do after you have exported it ?` I was thinking perhaps that is a possible solution to avoid losing data on ledgers that reach the limit ( 40 ).
Hmmm yea that is cool to undrop tables. Still, is there any provision to extend the limit of tables or as of now, it's 40 and that's it?

**Comment by aurghob33** [comment]
It's not possible to extend the limit of the tables from 40 for a ledger at the moment.
As discussed, one way to try overcoming the issue would be to export into a different ledger and to filter out the tables that are not needed. The caveat with exporting, however, would be that the doc ids and metadata will be different in the data exported to the new ledger.

**Comment by aurghob33** [comment]
Hi,

Closing out this issue as it has been open for a long time.
QLDB has limits as defined in [here](https://docs.aws.amazon.com/qldb/latest/developerguide/limits.html#limits.fixed).
Our documentation will be updated if this ever changes.

Meanwhile,
if you have further questions, please feel free to reopen this issue or a different issue.
