### ISSUE TITLE
I want to use "startTransaction" in the future

### ISSUE THREAD

**Issue by shushutochako** [awslabs/amazon-qldb-driver-nodejs#35]
Hi.
I used to build an application using "0.1.1-preview.2".
I'm trying to update to RC version. (1.0.0-rc.2)

Until now, I have controlled transactions flexibly using "startTransaction",
I was satisfied with the usability of "amazon-qldb-driver-nodejs"

```
const qldbSession: QldbSession = await qldbDriver.getSession();
const tx = await qldbSession.startTransaction();

// Various processing (including function that are not related to QLDB)
・
・
・

await tx.commit(); // or tx.abort();
await qldbSession.close();
```

But, With the release of the RC version, the specifications seems to have changed significantly.
Of particular note is the recommended use as follows:

```
qldbDriver.executeLambda(async (txn) => {
    // Various processing
}, () => log("Retrying due to OCC conflict..."));
```

I want to implement a flow that uses "startTransaction" as before for the following reasons.

- After starting a QLDB transaction, perform various function that are not related to QLDB
- I want to manually control transaction commit and abort
- I want to implement the application flow including commit and abort using async/await
     - "executeLambda" nests the whole thing.

I would like to continue to use "startTransaction" to flexibly control transactions.
However, I am worried that the feature will be removed as it is deprecated.

Do you have plans to add features with similar usability in the future?

**Comment by yohanmartin** [comment]
Hello @shushutochako, 
Thank you for reaching out. We would like to get into little more details about your use cases, specifically around a use case where you think `executeLambda` won't work or is not suitable.

I will address the points you raised for preferring `startTransaction` over executeLambda:

---

 _"After starting a QLDB transaction, perform various function that are not related to QLDB"_  

`executeLambda` allows you to do that. In fact, when doing executeLambda, the driver does the exact same steps that you are doing manually and in the exact same sequence i.e. the driver does `startSession`, followed by `startTransaction`, then execute the block of code you passed as an argument to executeLambda, and then  finally `commitTransaction`.  
But the other important advantage of using executeLambda is that it has a retry mechanism against failures which might occur during  execution of the transaction.

---

_"I want to manually control transaction commit and abort"_

In `executeLambda`,  you can choose to abort the transaction(Example provided below).  The `commit transaction` is done after the code block, passed as an argument, is executed.

---

_"I want to implement the application flow including commit and abort using async/await
`executeLambda` nests the whole thing."_

We would like more information on this particular point to see if there is a use case which is not covered. But in general, the `executeLambda` returns a promise and you can await on this promise to get the *similar* application flow you expect with manual transactions.

---

Here is the `executeLambda` equivalent of  the code you provided in your comment(the first snippet)

```
await driver.executeLambda(async (txn) => {
        // Various processing (including function that are not related to QLDB)
        ..
        ..
        ..
       //Once the entire code block is executed, driver will internally do `txn.commit()`
}, () => log("Retrying due to OCC conflict..."));
```

In case where you decide to abort the transaction, you can do that from inside `executeLambda`

```
await driver.executeLambda(async (txn) => {
        // Various processing (including function that are not related to QLDB)
        ..
        ..
       //At some point, let's say your condition to abort the transaction is met 
       if (someConditionToAbortTxnIsMet) {
              //Driver will abort the transaction and will not proceed with the rest of the code in this method. 
              txn.abort();
       }
       ..
       ..
       //If the execution reaches here (i.e. the abort is not done), driver will do `txn.commit()`
}, () => log("Retrying due to OCC conflict..."));
```

To summarize here is how your overall application flow would look like:

```
//Some application processing code

let result: Result = await driver.executeLambda(async (txn) => {
    // Various processing (including function that are not related to QLDB)
    ..
    ..
    ..
   //If some condition is met then  explicitly do txn.abort() else at the end of this block, txn.commit() will be done automatically.
    
},  () => log("Retrying due to OCC conflict..."));

//The other application flow which might use the result returned from the above code
```
---

Finally, one of the reasons we recommend using `executeLambda` is that it does not require you to think about handling failures which are not directly related to your application code i.e. Failures due to network issues, failures due to timeouts, failures due to throttling etc. ([List of common errors](https://docs.aws.amazon.com/qldb/latest/developerguide/driver-errors.html)).  With manual transactions, you need to build almost similar retry mechanism that we have built in `executeLambda` (we will keep improving on the retry mechanism as needed).

---

If still there are  use cases which `executeLambda` is not suited for, we would like to hear more details about those cases.

Thank You.

**Comment by yohanmartin** [comment]
Hello @shushutochako,
Wanted to follow-up on this to understand if the above reply helped you. Also, did you migrate your application to the newer version and is it meeting your expectation?

Thank You.

**Comment by shushutochako** [comment]
Hi. @yohanmartin .

I forgot to reply. I'm sorry.
I understood that I needed to migrate to executeLambda.

I am in the process of moving to exameLambda.

If you find any issues using exacuteLambda in the future, we will ask you again.
Thank you for answering.
