### ISSUE TITLE
BadRequestException: No open transaction - when using the result of one query for another

### ISSUE THREAD

**Issue by stephenirven** [awslabs/amazon-qldb-driver-nodejs#40]
Hello,

I'm having some trouble using multiple queries in a transaction, where the result of one query needs to be used in another (for example to use the ID generated in a subsequent query. I'm getting "BadRequestException: No open transaction" when running the second dependent query in a .then chain.

`    
Unhandled Promise Rejection	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"BadRequestException: No open transaction","reason":{"errorType":"BadRequestException","errorMessage":"No open transaction","code":"BadRequestException","message":"No open transaction","time":"2020-07-12T20:51:51.081Z","requestId":"89gRzMUvooa1VodxP8RRRM, 89gRzMUvooa1VodxP8RRRM","statusCode":400,"retryable":false,
`

The queries run correctly independently, or when run concurrently via Promise.all instead of .then. Logging the transaction at this point shows "_isClosed":false

code example:
```
const qldbDriver = await getQldbDriver();
    await qldbDriver.executeLambda(
      async (txn) => {
        Promise.all([
          txn
            .execute(
              `SELECT buildingId, b.* FROM building AS b BY buildingId where b.name = ?`,
              "building1"
            )
            .then(
              (result) => {
                const resultList = result.getResultList();
                if (resultList.length != 0) {
                  const building = result.getResultList()[0];

                  const { buildingId } = building;
                  const statement = `INSERT INTO location ?`;

/////// "_isClosed":false,

                  console.log(JSON.stringify(txn));

/////// This statement throws BadRequestException - No open transaction ///////

                  txn.execute(statement, { ...details, buildingId });

///////
                } else {
                  Promise.reject("no matching building");
                }
              },
              (error) => {
                console.log("err:", error);
              }
            ),

        ]);
      },
      () => console.log("Retrying due to OCC conflict...")
    );
```

using version
"amazon-qldb-driver-nodejs": "^1.0.0",
nodejs10.x, lambda

**Comment by yohanmartin** [comment]
Hello @stephenirven,
Thank you for reaching out. Sorry for the delay in getting back.


***What is going wrong with the code you posted?***

At a high level, the executeLambda works the following way:

```
//The transactionLambda refers to the function you pass as an argument when calling the executeLambda method of the driver.

executeLambda(transactionLambda) {
    1. Start/Open the transaction on QLDB backend.
    2. Execute the transactionLambda function.
    3. Once the transactionLambda execution finishes (and there is no error thrown from that transactionLambda block), Commit the transaction.
}

```

In the current code you posted, the `Promises.all` is the last statement in transactionLambda and it [returns a promise(which will eventually resolve)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all). The driver picks this as an indication that the  transactionLambda has been executed successfully(since something(in this case, a promise) was returned and no error was thrown) and can go ahead with the next step, which is "commit the transaction". So, the driver then requests the Amazon QLDB backend to commit the transaction. When the transaction gets committed, the Amazon QLDB backend closes the transaction and does not accept any other activity for that transaction. 

Meanwhile, on your side, the statement execution in the first promise would have resolved before the commit happened, and the `.then` block of the first promise was triggered. The `INSERT` statement inside the `.then` block was attempted to be executed but the driver had already sent a commit before that, which had resulted in transaction closure.

One way to fix this issue(**specifically** for the code snippet you have shared), would be to add `await` before the `Promises.all` statement. This will ensure that the driver does not proceed with the next step till all the promises have resolved. 

```
const qldbDriver = await getQldbDriver();
    await qldbDriver.executeLambda(
      async (txn) => {
        //Adding await here
        await Promise.all([
          txn
            .execute(
   
           //Rest of the code stays the same

```



***Recommendation***
Disclaimer: This is our recommendation based on the code you presented. Feel free to discard it if the use case is more complicated than presented.

Dealing with `Promises.all` and the event loop mechanism can be tricky and may produce unexpected results, if not modeled correctly. With `Promises.all`, all the promises, passed as argument, start the execution at the same time and there is no  guarantee on the sequence of execution(eg: A second promise might resolve before the first promise gets resolved, etc.)

If your use case is more about *`read the record from table 1, process or do something with  the result and put it in table 2`*, then you can model that behavior without using `Promises.all`. Here is a code snippet that accomplishes the same thing but without using `Promises.all`.


```
qldbDriver.executeLambda( async (txn) => {
    let result: Result = await txn.execute( `SELECT buildingId, b.* FROM building AS b BY buildingId where b.name = ?`, "building1");
    let resultList = result.getResultList();
    let buildingResult: Result;
    if (resultList.length != 0) {
        const building = result.getResultList()[0];
        const statement = `INSERT INTO location ?`;
        //For testing, I changed the execute to insert building directly.
        // Please change it to whatever the insertion should be.
        buildingResult = await txn.execute(statement, building);
        return buildingResult.getResultList()[0];
    } else {
        //At this point, you might want to abort the transaction.
        txn.abort();
    }
});
```

With the above example, it becomes easy to reason about the execution flow. You can add the regular `try..catch` block around the `txn.execute(..)` or wherever suitable in your flow.
Having said that, we do understand that you might still have a use case for which `Promise.all` might be a better fit and you might want to use it.

Do let us know if adding `await` to your current code solves the problem and if the recommendation works for your use case.

Thank You.

**Comment by stephenirven** [comment]
Thanks for your detailed reply and explanation. That makes complete sense, and has resolved my current issue - looks like I confused myself in the series of async calls.
