### ISSUE TITLE
Why deeply nested callbacks?

### ISSUE THREAD

**Issue by nareshbhatia** [awslabs/amazon-qldb-driver-nodejs#41]
I am just starting out with the Node driver and surprised by the mixed use of async/await, then() and callbacks in all the learning materials. For example:

```
export async function createTable(txn: TransactionExecutor, tableName: string): Promise<number> {
    const statement: string = `CREATE TABLE ${tableName}`;
    return await txn.execute(statement).then((result: Result) => {
        log(`Successfully created table ${tableName}.`);
        return result.getResultList().length;
    });
}
```
Can't this be simplified to:

```
export async function createTable(txn: TransactionExecutor, tableName: string): Promise<number> {
    const statement: string = `CREATE TABLE ${tableName}`;
    const result = await txn.execute(statement);
    log(`Successfully created table ${tableName}.`);
    return result.getResultList().length;
}
```

Here's an extreme example (commonly referred to as "callback hell"):

```
const main = function() {
  //Pass no configuration in the second argument and use the default settings
  const driver = new qldb.QldbDriver('quick-start', {});
  console.log("Create table People");
  createTable(driver, function() {
    console.log("Create index on firstName");
    createIndex(driver, function() {
      console.log("Insert document");
      insertDocument(driver, function() {
        console.log("Fetch document");
        fetchDocuments(driver, function() {
          console.log("Update document");
          updateDocuments(driver, function() {
            console.log("Fetch document after update");
            fetchDocuments(driver, function() {
              driver.close();
            })
          });
        });
      });
    });
  });
}
```

Is there a subtle reason for doing this that I have completely missed? I understand that this is the original pattern that nodejs used, but it would help tremendously if the learning material was simplified to use the modern async/await syntax. This will allow people to focus better on the underlying concepts.

**Comment by yohanmartin** [comment]
Hello @nareshbhatia,
Thank you for the feedback. We are working on simplifying the learning material and specifically the DMV sample app we have out there. Also, there is no reason(subtle or otherwise) to use callbacks over async/await. 

With regards to the last example of callback hell, while writing the [quick start tutorial](https://docs.aws.amazon.com/qldb/latest/developerguide/driver-quickstart-nodejs.html), the idea was to walk through each phase (create table, create index, insert document etc.) step-by-step, with each step getting a reference to the next step. We wanted to highlight the sequence aspect (first create the table, if successful, create index,  if successful,  insert document etc.) and callbacks seemed to do the work well  for the purpose but when it all came out together, it turned into callback hell. I agree that we can put an alternate version which uses async/await. We have noted this and will work toward that!

Again, we appreciate the feedback and would like to know more on what can be improved.

Thank You.

**Comment by nareshbhatia** [comment]
Thank you for confirming @yohanmartin. I can sleep in peace now :-)

One other suggestion, for the DMV example, might be to make it a continuously running server rather than disconnected modules - because that's a more realistic server. Could be an express app driven using an API. That way you can provide better guidance on creating the driver only once, providing it to various APIs and closing it when the server exits (I assume that would be the recommended lifecycle for the driver).
