### ISSUE TITLE
StartTransactionError after approx 20 minutes of inactivity

### ISSUE THREAD

**Issue by haggalin** [awslabs/amazon-qldb-driver-nodejs#51]
**Description**
I'm getting an error on version 2.0.0:
```
{
  "name": "StartTransactionError",
  "cause": {
    "message": "The parameter SessionToken is not valid",
    "code": "BadRequestException",
    "time": "2020-11-13T08:59:20.711Z",
    "requestId": "8PdWbUjmlTdGVFEZZzsy27",
    "statusCode": 400,
    "retryable": false
  }
}
```
which occurs during a call to `executeLambda(...)` after around 20 minutes of inactivity on the driver. The driver will retry the execution until it passes the retry limit and then throw this error.

I assume the 20 minutes is actually more like 13-17 minutes which is the session lifetime according to this:
https://docs.aws.amazon.com/qldb/latest/developerguide/driver-session-management.html#driver-session-mgmt.expiration

**Two questions:**
1. The expectations was that the driver would handle invalid session tokens automatically or is it entirely up to the client application to implement that?
2. Also the error is marked as `retryable = false` then why is it retrying the execution?

**Workaround**
My current workaround is to catch the exception `StartTransactionError`, close the driver, create a new instance of it and manually run again the `executeLambda(...)`

**Driver configuaration**
The configuration I have for the driver, is just similar to what is recommended here https://docs.aws.amazon.com/qldb/latest/developerguide/getting-started.nodejs.html#nodejs-config:
```
const maxConcurrentTransactions = 50;
const agent = new https.Agent({
    keepAlive: true,
    maxSockets: maxConcurrentTransactions
});
const driverConfig: ClientConfiguration = {
    httpOptions: { agent },
    region: "eu-west-1",
    credentials: {
        accessKeyId: "<access-key-id-from-sts-assume-role-response>",
        secretAccessKey: "<secret-access-key-from-sts-assume-role-response>",
        sessionToken: "<session-token-from-sts-assume-role-response>"
    }
};
const retryConfig = new RetryConfig(4, (attempt, error, transactionId) => {
    const backoffTimeMs = attempt * 500;
    logger.info({ attempt, transactionId, error, backoffTimeMs }, 'Retrying QLDB execution');
    return backoffTimeMs;
});
const driver = new QldbDriver("ledger-name", driverConfig, maxConcurrentTransactions, retryConfig);
....
```

**Comment by yohanmartin** [comment]
Thank you for reaching out. 

> The expectation was that the driver would handle invalid session tokens automatically or is it entirely up to the client application to implement that?

The expectation is correct. But we recently found a bug on service side which causes this issue and sends `BadRequestException` instead of `InvalidSessionException`. We have fixed the issue and will deploy the fix soon. Till that time, unfortunately, the driver will continue to receive `BadRequestException` instead of `InvalidSessionException`. Once fixed, the driver will retry the transaction by selecting another session from the pool, as long as there are sessions in the pool. If there are no more sessions in the pool, the driver will throw "SessionPoolEmptyError" (Note: You can have a look at the [`getSession`](https://github.com/awslabs/amazon-qldb-driver-nodejs/blob/master/src/QldbDriver.ts#L221) method and the place where it throws [`SessionPoolEmptyError`](https://github.com/awslabs/amazon-qldb-driver-nodejs/blob/master/src/QldbDriver.ts#L243)). If, during retries, it hits the retry limit, then the driver will bubble up the original exception. 

As you have noted, this bug is manifested for a bursty traffic pattern(traffic followed by a period of rest) and particularly for all the requests made on the session a minute after the session has expired. If in anyway, you can have a consistent traffic on the driver and particularly, if your requests happen to use the sessions within a minute of its expiry, the driver should work fine. This may not be possible if there is no way to have a consistent traffic.


---

> Also the error is marked as retryable = false then why is it retrying the execution?

If you look at the [`StartTransaction`](https://github.com/awslabs/amazon-qldb-driver-nodejs/blob/master/src/QldbSession.ts#L115) method, we specifically check for `isBadRequestException`. The reason is, ideally, a `BadRequestException` can happen on `StartTransaction` request only if someone tries to start another transaction on a session that already has an open but stale (more on this later) transaction. So while the `retryable` flag was false, we wanted to build a mechanism to handle this case. So the defense mechanism in driver is: Try to start a transaction on a session. If the start transaction request fails because of `BadRequestException`, it is because of an already open transaction. In this case, send an abort transaction request on that session to close the previous (but stale) transaction and retry the start transaction request with the same session. Whereas, if the start transaction request fails because of `InvalidSessionException`, remove this session from the pool and  try the transaction with another session from the pool. 

As you would have guessed, the bug, pointed out above, changes this behavior, because now the `BadRequestException` can be thrown when the session has expired and hence, the driver goes in the retry loop till it has hit the retry limit.

*What causes stale transaction on a session?*

A stale transaction is transaction that did not explicitly receive a commit or an abort request. The easiest example is let's say, you ask the driver to execute one transaction for you. The driver sends a `StartTransaction` request to QLDB. QLDB opens a transaction on the backend, but for some reason, the driver did not receive the response or some network exception thrown. The driver decides to retry and when it retries, it sends the `StartTransaction` request again over the same session. This time the AWS QLDB throws a `BadRequestException` with the message `Transaction already open`.

---
We are sorry for the trouble this has caused and the work arounds you've had to do. I will update this ticket as soon as we deploy the fix.

Do let us know if you have more questions.

Thank You.

**Comment by haggalin** [comment]
Thanks for your very detailed answers! 

It's good that the bug has already been resolved. We'll keep our workaround as it is for now then and wait for the deployment.

**Comment by Salmandabbakuti** [comment]
Is this bug resolved? I'm experiencing the same error.
```
BadRequestException: "The parameter SessionToken is not valid",

```
As they mention in docs for v2.0, 
```
 By default, the QldbDriver object manages the session pool. When you make a call to run a transaction, the driver does the following steps:

If a session is available in the pool, the driver uses it to run a transaction.

If no session is available in the pool, the driver creates a new session and uses it to run a transaction.


If you encounter this exception, we recommend that you acquire a new session and retry the transaction. We also recommend using the latest version of the QLDB driver, which manages the session pool and its health on the application's behalf.
```

sessions need to be maintained by the driver itself  and create a new session if the session has expired

**Comment by saumehta9** [comment]
Hello, 
The fix for this issue has been deployed completely to all regions as of December 7 2020.
You should no longer face this issue. Please let us know if you need help with anything.

**Comment by saumehta9** [comment]
@haggalin, Please reopen the issue if you still face problems.

**Comment by Salmandabbakuti** [comment]
Fix means, we don't have to handle the session expiries from now on and driver handles it all right?

**Comment by saumehta9** [comment]
@Salmandabbakuti 

> Fix means, we don't have to handle the session expiries from now on and driver handles it all right?

Yes, that is correct.
